SUBROUTING MWT.TEST.SUBR
** INFORMATION ****************************************************************
* Routine Name   : MWT.TEST
*         Type   : PROGRAM
*         Params :
*         Loc    : MWT.BP
* -----------------------------------------------------------------------------
* Info Updated   : 20191220 at 15.44.57 in MWT-QM-DEV by sales
*                : on ldn-srv-ubnt01 (Linux)
* -----------------------------------------------------------------------------
*
   CRT "MWT.TEST.SUBR"
   CRT SYSTEM(1047)
   CRT SYSTEM(33)
   CRT SYSTEM(1002)
   CALL MWT.TEST.SUBR2
   RETURN
END
