SUBROUTINE MWT.TEST.SUBR
** INFORMATION ****************************************************************
* Routine Name   : MWT.TEST.SUBR
*         Type   : SUBROUTINE
*         Params :
*         Loc    : MWT.BP
** AUDIT **********************************************************************
* Info Updated   : 20200313 at 13.51.39 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************

$INSERT UTIL.BP I_UTIL.H
   CALL U_INITIALISE("")

   CALL U_CRT.INFO("MWT.TEST.SUBR", "MWT.TEST.SUBR")
   CALL U_CRT.INFO("SYSTEM-1047", SYSTEM(1047))
   CALL U_CRT.INFO("SYSTEM-33", SYSTEM(33))
   CALL U_CRT.INFO("SYSTEM-1002", SYSTEM(1002))
   CALL U_CRT.RECORD(SYSTEM(1002))
   CALL MWT.TEST.SUBR2
   RETURN
END
