SUBROUTINE MWT.TEST.SUBR
** INFORMATION ****************************************************************
* Routine Name   : MWT.TEST.SUBR
*         Type   : SUBROUTINE
*         Params :
*         Loc    : MWT.BP
* -----------------------------------------------------------------------------
* Info Updated   : 20200121 at 15.43.59 in MWT-QM-DEV by sales
*                : on ldn-srv-ubnt01 (Linux)
* -----------------------------------------------------------------------------
*
   CALL U_CRT.INFO("MWT.TEST.SUBR", "MWT.TEST.SUBR")
   CALL U_CRT.INFO("SYSTEM-1047", SYSTEM(1047))
   CALL U_CRT.INFO("SYSTEM-33", SYSTEM(33))
   CALL U_CRT.INFO("SYSTEM-1002", SYSTEM(1002))
   CALL U_CRT.RECORD(SYSTEM(1002))
   CALL MWT.TEST.SUBR2
   RETURN
END
