** INFORMATION ****************************************************************
*    Insert Name : F_BP.H - BP
*           Type : INSERT
*       Filename : BP
*         Prefix : BP$
** AUDIT **********************************************************************
*   Info Updated : 20210411 at 16.29.33 in MWT-QM-DEV by matttownsend
*                : on silicon.local (Mac)
*******************************************************************************
equate BP$FILE.NAME to "BP"
equate BP$FILENAME to "BP"
equate BP$PARAMETERS to 1
equate BP$PARAMETERS$LEN to "15"
equate BP$PARAMETERS$MASK to ""
equate BP$PARAMETERS$LABEL to ""
