** INFORMATION ****************************************************************
*    Insert Name : F_LOGS.H - BP
*           Type : INSERT
*       Filename : LOGS
*         Prefix : S_L_
** AUDIT **********************************************************************
*   Info Updated : 20210320 at 17.08.30 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_L_FILE.NAME to "LOGS"
equate S_L_FILENAME to "LOGS"
equate S_L_LOG to 1
equate S_L_LOG$LEN to "15"
equate S_L_LOG$MASK to ""
equate S_L_LOG$LABEL to ""
