** INFORMATION ****************************************************************
*    Insert Name : F_LOGS.H - BP
*           Type : INSERT
*       Filename : LOGS
*         Prefix : S_L_
** AUDIT **********************************************************************
*   Info Updated : 20210411 at 16.29.36 in MWT-QM-DEV by matttownsend
*                : on silicon.local (Mac)
*******************************************************************************
equate S_L_FILE.NAME to "LOGS"
equate S_L_FILENAME to "LOGS"
equate S_L_LOG to 1
equate S_L_LOG$LEN to "15"
equate S_L_LOG$MASK to ""
equate S_L_LOG$LABEL to ""
