** INFORMATION ****************************************************************
*    Insert Name : F_LOGS.H - BP
*           Type : INSERT
*       Filename : LOGS
*         Prefix : S_L_
** AUDIT **********************************************************************
*   Info Updated : 20210301 at 15.46.53 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_L_FILE.NAME to "LOGS"
equate S_L_LOG to 1
