** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.TEMP.H - BP
*           Type : INSERT
*       Filename : SIENA.TEMP
*         Prefix : S_TEMP.
** AUDIT **********************************************************************
*   Info Updated : 20210301 at 15.46.54 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_TEMP.FILE.NAME to "SIENA.TEMP"
equate S_TEMP.OUTPUT to 1
