** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.TXN.OUT.H - BP
*           Type : INSERT
*       Filename : SIENA.TXN.OUT
*         Prefix : S_TXN_OUT_
** AUDIT **********************************************************************
*   Info Updated : 20210320 at 17.08.31 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_TXN_OUT_FILE.NAME to "SIENA.TXN.OUT"
equate S_TXN_OUT_FILENAME to "SIENA.TXN.OUT"
equate S_TXN_OUT_CONTENT to 1
equate S_TXN_OUT_CONTENT$LEN to "15"
equate S_TXN_OUT_CONTENT$MASK to ""
equate S_TXN_OUT_CONTENT$LABEL to ""
