** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.CACHE.H - BP
*           Type : INSERT
*       Filename : SIENA.CACHE
*         Prefix : S_CACHE_
** AUDIT **********************************************************************
*   Info Updated : 20210318 at 13.05.48 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_CACHE_FILE.NAME to "SIENA.CACHE"
equate S_CACHE_FILENAME to "SIENA.CACHE"
equate S_CACHE_OBJECT to 1
equate S_CACHE_OBJECT$LEN to "35"
equate S_CACHE_OBJECT$MASK to ""
equate S_CACHE_OBJECT$LABEL to ""
equate S_CACHE_FIELD to 2
equate S_CACHE_FIELD$LEN to "35"
equate S_CACHE_FIELD$MASK to ""
equate S_CACHE_FIELD$LABEL to ""
equate S_CACHE_VALUE to 3
equate S_CACHE_VALUE$LEN to "35"
equate S_CACHE_VALUE$MASK to ""
equate S_CACHE_VALUE$LABEL to ""
equate S_CACHE_DATE to 4
equate S_CACHE_DATE$LEN to "12"
equate S_CACHE_DATE$MASK to "D"
equate S_CACHE_DATE$LABEL to ""
equate S_CACHE_TIME to 5
equate S_CACHE_TIME$LEN to "35"
equate S_CACHE_TIME$MASK to "MT"
equate S_CACHE_TIME$LABEL to ""
equate S_CACHE_USER to 6
equate S_CACHE_USER$LEN to "35"
equate S_CACHE_USER$MASK to ""
equate S_CACHE_USER$LABEL to ""
