** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.CACHE.H - BP
*           Type : INSERT
*       Filename : SIENA.CACHE
*         Prefix : S_CACHE_
** AUDIT **********************************************************************
*   Info Updated : 20210228 at 14.11.28 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_CACHE_FILE.NAME to "SIENA.CACHE"
equate S_CACHE_OBJECT to 1
equate S_CACHE_FIELD to 2
equate S_CACHE_VALUE to 3
equate S_CACHE_DATE to 4
equate S_CACHE_TIME to 5
equate S_CACHE_USER to 6
