** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.DEST.H - BP
*           Type : INSERT
*       Filename : SIENA.DEST
*         Prefix : S_DEST_
** AUDIT **********************************************************************
*   Info Updated : 20210301 at 15.46.54 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_DEST_FILE.NAME to "SIENA.DEST"
equate S_DEST_OUTPUT to 1
