** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.IN.H - BP
*           Type : INSERT
*       Filename : SIENA.IN
*         Prefix : S_IN.
** AUDIT **********************************************************************
*   Info Updated : 20210411 at 16.29.36 in MWT-QM-DEV by matttownsend
*                : on silicon.local (Mac)
*******************************************************************************
equate S_IN.FILE.NAME to "SIENA.IN"
equate S_IN.FILENAME to "SIENA.IN"
equate S_IN.DATA to 1
equate S_IN.DATA$LEN to "35"
equate S_IN.DATA$MASK to ""
equate S_IN.DATA$LABEL to ""
