** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.DEST.H - BP
*           Type : INSERT
*       Filename : SIENA.DEST
*         Prefix : S_DEST_
** AUDIT **********************************************************************
*   Info Updated : 20210322 at 09.52.02 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_DEST_FILE.NAME to "SIENA.DEST"
equate S_DEST_FILENAME to "SIENA.DEST"
equate S_DEST_OUTPUT to 1
equate S_DEST_OUTPUT$LEN to "15"
equate S_DEST_OUTPUT$MASK to ""
equate S_DEST_OUTPUT$LABEL to ""
