** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.TXN.TEMPLATES.H - BP
*           Type : INSERT
*       Filename : SIENA.TXN.TEMPLATES
*         Prefix : S_TXN_TEMPLATE_
** AUDIT **********************************************************************
*   Info Updated : 20210301 at 15.46.55 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_TXN_TEMPLATE_FILE.NAME to "SIENA.TXN.TEMPLATES"
equate S_TXN_TEMPLATE_CONTENT to 1
