** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.TXN.TEMPLATES.H - BP
*           Type : INSERT
*       Filename : SIENA.TXN.TEMPLATES
*         Prefix : S_TXN_TEMPLATE_
** AUDIT **********************************************************************
*   Info Updated : 20210318 at 13.05.49 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_TXN_TEMPLATE_FILE.NAME to "SIENA.TXN.TEMPLATES"
equate S_TXN_TEMPLATE_FILENAME to "SIENA.TXN.TEMPLATES"
equate S_TXN_TEMPLATE_CONTENT to 1
equate S_TXN_TEMPLATE_CONTENT$LEN to "15"
equate S_TXN_TEMPLATE_CONTENT$MASK to ""
equate S_TXN_TEMPLATE_CONTENT$LABEL to ""
