** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.PROCESSED.H - BP
*           Type : INSERT
*       Filename : SIENA.PROCESSED
*         Prefix : S_PROC_
** AUDIT **********************************************************************
*   Info Updated : 20210322 at 09.52.04 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_PROC_FILE.NAME to "SIENA.PROCESSED"
equate S_PROC_FILENAME to "SIENA.PROCESSED"
equate S_PROC_OUTPUT to 1
equate S_PROC_OUTPUT$LEN to "15"
equate S_PROC_OUTPUT$MASK to ""
equate S_PROC_OUTPUT$LABEL to ""
