** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.PROCESSED.H - BP
*           Type : INSERT
*       Filename : SIENA.PROCESSED
*         Prefix : S_PROC_
** AUDIT **********************************************************************
*   Info Updated : 20210301 at 15.46.54 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_PROC_FILE.NAME to "SIENA.PROCESSED"
equate S_PROC_OUTPUT to 1
