** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.TEMP.H - BP
*           Type : INSERT
*       Filename : SIENA.TEMP
*         Prefix : S_TEMP.
** AUDIT **********************************************************************
*   Info Updated : 20210318 at 13.05.49 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_TEMP.FILE.NAME to "SIENA.TEMP"
equate S_TEMP.FILENAME to "SIENA.TEMP"
equate S_TEMP.OUTPUT to 1
equate S_TEMP.OUTPUT$LEN to "15"
equate S_TEMP.OUTPUT$MASK to ""
equate S_TEMP.OUTPUT$LABEL to ""
