** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.IN.H - BP
*           Type : INSERT
*       Filename : SIENA.IN
*         Prefix : S_IN.
** AUDIT **********************************************************************
*   Info Updated : 20210301 at 15.46.54 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_IN.FILE.NAME to "SIENA.IN"
equate S_IN.DATA to 1
