** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.IN.H - BP
*           Type : INSERT
*       Filename : SIENA.IN
*         Prefix : S_IN.
** AUDIT **********************************************************************
*   Info Updated : 20210302 at 14.09.12 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_IN.FILE.NAME to "SIENA.IN"
equate S_IN.FILENAME to "SIENA.IN"
equate S_IN.DATA to 1
equate S_IN.DATA$LEN to "35"
equate S_IN.DATA$MASK to ""
equate S_IN.DATA$LABEL to ""
