** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.WCT.TEMPLATES.H - BP
*           Type : INSERT
*       Filename : UTIL.WCT.TEMPLATES
*         Prefix : W$TEMPLATE.
** AUDIT **********************************************************************
*   Info Updated : 20210301 at 15.46.56 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate W$TEMPLATE.FILE.NAME to "UTIL.WCT.TEMPLATES"
equate W$TEMPLATE.CONTENT to 1
