** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.WORKFILE.H - BP
*           Type : INSERT
*       Filename : UTIL.WORKFILE
*         Prefix : U$WRK.
** AUDIT **********************************************************************
*   Info Updated : 20210228 at 14.11.27 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U$WRK.FILE.NAME to "UTIL.WORKFILE"
equate U$WRK.REPORT to 1
