** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.CONFIG.H - BP
*           Type : INSERT
*       Filename : UTIL.CONFIG
*         Prefix : U$CONFIG.
** AUDIT **********************************************************************
*   Info Updated : 20210320 at 17.08.30 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U$CONFIG.FILE.NAME to "UTIL.CONFIG"
equate U$CONFIG.FILENAME to "UTIL.CONFIG"
equate U$CONFIG.DATA to 1
equate U$CONFIG.DATA$LEN to "15"
equate U$CONFIG.DATA$MASK to ""
equate U$CONFIG.DATA$LABEL to ""
