** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.SCRIPTS.H - BP
*           Type : INSERT
*       Filename : UTIL.SCRIPTS
*         Prefix : U_SCRIPTS.
** AUDIT **********************************************************************
*   Info Updated : 20210411 at 16.29.34 in MWT-QM-DEV by matttownsend
*                : on silicon.local (Mac)
*******************************************************************************
equate U_SCRIPTS.FILE.NAME to "UTIL.SCRIPTS"
equate U_SCRIPTS.FILENAME to "UTIL.SCRIPTS"
equate U_SCRIPTS.CONTENT to 1
equate U_SCRIPTS.CONTENT$LEN to "15"
equate U_SCRIPTS.CONTENT$MASK to ""
equate U_SCRIPTS.CONTENT$LABEL to ""
