** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.WCT.RESP.H - BP
*           Type : INSERT
*       Filename : UTIL.WCT.RESP
*         Prefix : W$RESP.
** AUDIT **********************************************************************
*   Info Updated : 20210411 at 16.29.37 in MWT-QM-DEV by matttownsend
*                : on silicon.local (Mac)
*******************************************************************************
equate W$RESP.FILE.NAME to "UTIL.WCT.RESP"
equate W$RESP.FILENAME to "UTIL.WCT.RESP"
equate W$RESP.CONTENT to 1
equate W$RESP.CONTENT$LEN to "15"
equate W$RESP.CONTENT$MASK to ""
equate W$RESP.CONTENT$LABEL to ""
