** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.SQL.SCRIPTS.H - BP
*           Type : INSERT
*       Filename : UTIL.SQL.SCRIPTS
*         Prefix : U_SQLSCR.
** AUDIT **********************************************************************
*   Info Updated : 20210302 at 14.09.11 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_SQLSCR.FILE.NAME to "UTIL.SQL.SCRIPTS"
equate U_SQLSCR.FILENAME to "UTIL.SQL.SCRIPTS"
equate U_SQLSCR.OUTPUT to 1
equate U_SQLSCR.OUTPUT$LEN to "15"
equate U_SQLSCR.OUTPUT$MASK to ""
equate U_SQLSCR.OUTPUT$LABEL to ""
