** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.WCT.RECV.H - BP
*           Type : INSERT
*       Filename : UTIL.WCT.RECV
*         Prefix : W$RECV.
** AUDIT **********************************************************************
*   Info Updated : 20210318 at 13.05.49 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate W$RECV.FILE.NAME to "UTIL.WCT.RECV"
equate W$RECV.FILENAME to "UTIL.WCT.RECV"
equate W$RECV.CONTENT to 1
equate W$RECV.CONTENT$LEN to "15"
equate W$RECV.CONTENT$MASK to ""
equate W$RECV.CONTENT$LABEL to ""
