** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.SQL.CMD.H - BP
*           Type : INSERT
*       Filename : UTIL.SQL.CMD
*         Prefix : U_SQLCMD.
** AUDIT **********************************************************************
*   Info Updated : 20210322 at 09.51.56 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_SQLCMD.FILE.NAME to "UTIL.SQL.CMD"
equate U_SQLCMD.FILENAME to "UTIL.SQL.CMD"
equate U_SQLCMD.COMMAND to 1
equate U_SQLCMD.COMMAND$LEN to "15"
equate U_SQLCMD.COMMAND$MASK to ""
equate U_SQLCMD.COMMAND$LABEL to ""
