** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.SQL.CMD.H - BP
*           Type : INSERT
*       Filename : UTIL.SQL.CMD
*         Prefix : U_SQLCMD.
** AUDIT **********************************************************************
*   Info Updated : 20210301 at 15.46.52 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_SQLCMD.FILE.NAME to "UTIL.SQL.CMD"
equate U_SQLCMD.COMMAND to 1
