** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.WORKFILE.H - BP
*           Type : INSERT
*       Filename : UTIL.WORKFILE
*         Prefix : U$WRK.
** AUDIT **********************************************************************
*   Info Updated : 20210318 at 13.05.47 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U$WRK.FILE.NAME to "UTIL.WORKFILE"
equate U$WRK.FILENAME to "UTIL.WORKFILE"
equate U$WRK.REPORT to 1
equate U$WRK.REPORT$LEN to "15"
equate U$WRK.REPORT$MASK to ""
equate U$WRK.REPORT$LABEL to ""
