** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.WCT.RESP.H - BP
*           Type : INSERT
*       Filename : UTIL.WCT.RESP
*         Prefix : W$RESP.
** AUDIT **********************************************************************
*   Info Updated : 20210301 at 15.46.55 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate W$RESP.FILE.NAME to "UTIL.WCT.RESP"
equate W$RESP.CONTENT to 1
