** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.WCT.TEMPLATES.H - BP
*           Type : INSERT
*       Filename : UTIL.WCT.TEMPLATES
*         Prefix : W$TEMPLATE.
** AUDIT **********************************************************************
*   Info Updated : 20210318 at 13.05.49 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate W$TEMPLATE.FILE.NAME to "UTIL.WCT.TEMPLATES"
equate W$TEMPLATE.FILENAME to "UTIL.WCT.TEMPLATES"
equate W$TEMPLATE.CONTENT to 1
equate W$TEMPLATE.CONTENT$LEN to "15"
equate W$TEMPLATE.CONTENT$MASK to ""
equate W$TEMPLATE.CONTENT$LABEL to ""
