** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.TRANSLATE.H - BP
*           Type : INSERT
*       Filename : UTIL.TRANSLATE
*         Prefix : U_TRNS.
** AUDIT **********************************************************************
*   Info Updated : 20210302 at 14.09.11 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_TRNS.FILE.NAME to "UTIL.TRANSLATE"
equate U_TRNS.FILENAME to "UTIL.TRANSLATE"
equate U_TRNS.MESSAGE to 1
equate U_TRNS.MESSAGE$LEN to "35"
equate U_TRNS.MESSAGE$MASK to ""
equate U_TRNS.MESSAGE$LABEL to ""
equate U_TRNS.UKTDATA to 2
equate U_TRNS.UKTDATA$LEN to "35"
equate U_TRNS.UKTDATA$MASK to ""
equate U_TRNS.UKTDATA$LABEL to ""
equate U_TRNS.NIPART to 3
equate U_TRNS.NIPART$LEN to "35"
equate U_TRNS.NIPART$MASK to ""
equate U_TRNS.NIPART$LABEL to ""
equate U_TRNS.NINAME to 4
equate U_TRNS.NINAME$LEN to "35"
equate U_TRNS.NINAME$MASK to ""
equate U_TRNS.NINAME$LABEL to ""
equate U_TRNS.BARCHARTCOM to 5
equate U_TRNS.BARCHARTCOM$LEN to "35"
equate U_TRNS.BARCHARTCOM$MASK to ""
equate U_TRNS.BARCHARTCOM$LABEL to ""
equate U_TRNS.SIENA_BC to 6
equate U_TRNS.SIENA_BC$LEN to "35"
equate U_TRNS.SIENA_BC$MASK to ""
equate U_TRNS.SIENA_BC$LABEL to ""
