** INFORMATION ****************************************************************
*    Insert Name : F_WEB.SESSIONS.H - BP
*           Type : INSERT
*       Filename : WEB.SESSIONS
*         Prefix : W$TOKEN.
** AUDIT **********************************************************************
*   Info Updated : 20210302 at 12.10.38 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate W$TOKEN.FILE.NAME to "WEB.SESSIONS"
equate W$TOKEN.APP.TOKEN to 1
equate W$TOKEN.CREATE.DATE to 2
equate W$TOKEN.CREATE.TIME to 3
equate W$TOKEN.UNIQUE.ID to 4
equate W$TOKEN.SESSION.TOKEN to 5
equate W$TOKEN.USERNAME to 6
equate W$TOKEN.PASSWORD to 7
equate W$TOKEN.USER.IP to 8
equate W$TOKEN.USER.HOST to 9
equate W$TOKEN.WS.IP to 10
equate W$TOKEN.WS.HOST to 11
equate W$TOKEN.APP.IP to 12
equate W$TOKEN.APP.HOST to 13
equate W$TOKEN.ISSUED to 14
equate W$TOKEN.EXPIRY to 15
