** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.CONFIG.H - BP
*           Type : INSERT
*       Filename : UTIL.CONFIG
*         Prefix : U$CONFIG.
** AUDIT **********************************************************************
*   Info Updated : 20210301 at 15.46.53 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U$CONFIG.FILE.NAME to "UTIL.CONFIG"
equate U$CONFIG.DATA to 1
