** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.SQL.RESPONSE.H - BP
*           Type : INSERT
*       Filename : UTIL.SQL.RESPONSE
*         Prefix : U_SQLREP_
** AUDIT **********************************************************************
*   Info Updated : 20210302 at 14.09.11 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_SQLREP_FILE.NAME to "UTIL.SQL.RESPONSE"
equate U_SQLREP_FILENAME to "UTIL.SQL.RESPONSE"
equate U_SQLREP_OUTPUT to 1
equate U_SQLREP_OUTPUT$LEN to "15"
equate U_SQLREP_OUTPUT$MASK to ""
equate U_SQLREP_OUTPUT$LABEL to ""
