** INFORMATION ****************************************************************
*    Insert Name : F_WEB.CREDENTIALS.H - BP
*           Type : INSERT
*       Filename : WEB.CREDENTIALS
*         Prefix : W$CRED.
** AUDIT **********************************************************************
*   Info Updated : 20210318 at 13.05.50 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate W$CRED.FILE.NAME to "WEB.CREDENTIALS"
equate W$CRED.FILENAME to "WEB.CREDENTIALS"
equate W$CRED.USERNAME to 1
equate W$CRED.USERNAME$LEN to "20"
equate W$CRED.USERNAME$MASK to ""
equate W$CRED.USERNAME$LABEL to "User Name"
equate W$CRED.PASSWORD to 2
equate W$CRED.PASSWORD$LEN to "20"
equate W$CRED.PASSWORD$MASK to "L"
equate W$CRED.PASSWORD$LABEL to "Password"
equate W$CRED.FIRSTNAME to 3
equate W$CRED.FIRSTNAME$LEN to "10"
equate W$CRED.FIRSTNAME$MASK to ""
equate W$CRED.FIRSTNAME$LABEL to "First name"
equate W$CRED.LASTNAME to 4
equate W$CRED.LASTNAME$LEN to "10"
equate W$CRED.LASTNAME$MASK to ""
equate W$CRED.LASTNAME$LABEL to "Family Name"
equate W$CRED.KNOWNAS to 5
equate W$CRED.KNOWNAS$LEN to "8"
equate W$CRED.KNOWNAS$MASK to ""
equate W$CRED.KNOWNAS$LABEL to "Known as"
equate W$CRED.EMAIL to 6
equate W$CRED.EMAIL$LEN to "35"
equate W$CRED.EMAIL$MASK to ""
equate W$CRED.EMAIL$LABEL to "email"
equate W$CRED.ISSUED to 7
equate W$CRED.ISSUED$LEN to "35"
equate W$CRED.ISSUED$MASK to "EA"
equate W$CRED.ISSUED$LABEL to "Issued"
equate W$CRED.EXPIRY to 8
equate W$CRED.EXPIRY$LEN to "35"
equate W$CRED.EXPIRY$MASK to "EA"
equate W$CRED.EXPIRY$LABEL to "Expires"
equate W$CRED.MACHINE to 9
equate W$CRED.MACHINE$LEN to "35"
equate W$CRED.MACHINE$MASK to ""
equate W$CRED.MACHINE$LABEL to "Machine"
equate W$CRED.ROLE to 10
equate W$CRED.ROLE$LEN to "15"
equate W$CRED.ROLE$MASK to ""
equate W$CRED.ROLE$LABEL to "User Role"
