** INFORMATION ****************************************************************
*    Insert Name : F_WEB.SESSIONS.H - BP
*           Type : INSERT
*       Filename : WEB.SESSIONS
*         Prefix : W$TOKEN.
** AUDIT **********************************************************************
*   Info Updated : 20210411 at 16.29.38 in MWT-QM-DEV by matttownsend
*                : on silicon.local (Mac)
*******************************************************************************
equate W$TOKEN.FILE.NAME to "WEB.SESSIONS"
equate W$TOKEN.FILENAME to "WEB.SESSIONS"
equate W$TOKEN.APP.TOKEN to 1
equate W$TOKEN.APP.TOKEN$LEN to "35"
equate W$TOKEN.APP.TOKEN$MASK to ""
equate W$TOKEN.APP.TOKEN$LABEL to ""
equate W$TOKEN.CREATE.DATE to 2
equate W$TOKEN.CREATE.DATE$LEN to "35"
equate W$TOKEN.CREATE.DATE$MASK to "D"
equate W$TOKEN.CREATE.DATE$LABEL to ""
equate W$TOKEN.CREATE.TIME to 3
equate W$TOKEN.CREATE.TIME$LEN to "35"
equate W$TOKEN.CREATE.TIME$MASK to "MT"
equate W$TOKEN.CREATE.TIME$LABEL to ""
equate W$TOKEN.UNIQUE.ID to 4
equate W$TOKEN.UNIQUE.ID$LEN to "35"
equate W$TOKEN.UNIQUE.ID$MASK to ""
equate W$TOKEN.UNIQUE.ID$LABEL to ""
equate W$TOKEN.SESSION.TOKEN to 5
equate W$TOKEN.SESSION.TOKEN$LEN to "35"
equate W$TOKEN.SESSION.TOKEN$MASK to ""
equate W$TOKEN.SESSION.TOKEN$LABEL to ""
equate W$TOKEN.USERNAME to 6
equate W$TOKEN.USERNAME$LEN to "35"
equate W$TOKEN.USERNAME$MASK to ""
equate W$TOKEN.USERNAME$LABEL to ""
equate W$TOKEN.PASSWORD to 7
equate W$TOKEN.PASSWORD$LEN to "35"
equate W$TOKEN.PASSWORD$MASK to "L"
equate W$TOKEN.PASSWORD$LABEL to ""
equate W$TOKEN.USER.IP to 8
equate W$TOKEN.USER.IP$LEN to "35"
equate W$TOKEN.USER.IP$MASK to ""
equate W$TOKEN.USER.IP$LABEL to ""
equate W$TOKEN.USER.HOST to 9
equate W$TOKEN.USER.HOST$LEN to "35"
equate W$TOKEN.USER.HOST$MASK to ""
equate W$TOKEN.USER.HOST$LABEL to ""
equate W$TOKEN.WS.IP to 10
equate W$TOKEN.WS.IP$LEN to "35"
equate W$TOKEN.WS.IP$MASK to ""
equate W$TOKEN.WS.IP$LABEL to ""
equate W$TOKEN.WS.HOST to 11
equate W$TOKEN.WS.HOST$LEN to "35"
equate W$TOKEN.WS.HOST$MASK to ""
equate W$TOKEN.WS.HOST$LABEL to ""
equate W$TOKEN.APP.IP to 12
equate W$TOKEN.APP.IP$LEN to "35"
equate W$TOKEN.APP.IP$MASK to ""
equate W$TOKEN.APP.IP$LABEL to ""
equate W$TOKEN.APP.HOST to 13
equate W$TOKEN.APP.HOST$LEN to "35"
equate W$TOKEN.APP.HOST$MASK to ""
equate W$TOKEN.APP.HOST$LABEL to ""
equate W$TOKEN.ISSUED to 14
equate W$TOKEN.ISSUED$LEN to "35"
equate W$TOKEN.ISSUED$MASK to "EA"
equate W$TOKEN.ISSUED$LABEL to ""
equate W$TOKEN.EXPIRY to 15
equate W$TOKEN.EXPIRY$LEN to "35"
equate W$TOKEN.EXPIRY$MASK to "EA"
equate W$TOKEN.EXPIRY$LABEL to ""
equate W$TOKEN.EXPIRY.RAW to 15
equate W$TOKEN.EXPIRY.RAW$LEN to "35"
equate W$TOKEN.EXPIRY.RAW$MASK to ""
equate W$TOKEN.EXPIRY.RAW$LABEL to ""
equate W$TOKEN.ROLE to 16
equate W$TOKEN.ROLE$LEN to "15"
equate W$TOKEN.ROLE$MASK to ""
equate W$TOKEN.ROLE$LABEL to "User Role"
equate W$TOKEN.BRAND to 17
equate W$TOKEN.BRAND$LEN to "15"
equate W$TOKEN.BRAND$MASK to ""
equate W$TOKEN.BRAND$LABEL to "User Role"
