** INFORMATION ****************************************************************
*    Insert Name : F_WEB.CREDENTIALS.IDX.H - BP
*           Type : INSERT
*       Filename : WEB.CREDENTIALS.IDX
*         Prefix : W$CRED_IDX.
** AUDIT **********************************************************************
*   Info Updated : 20210411 at 16.29.39 in MWT-QM-DEV by matttownsend
*                : on silicon.local (Mac)
*******************************************************************************
equate W$CRED_IDX.FILE.NAME to "WEB.CREDENTIALS.IDX"
equate W$CRED_IDX.FILENAME to "WEB.CREDENTIALS.IDX"
equate W$CRED_IDX.ID to 1
equate W$CRED_IDX.ID$LEN to "20"
equate W$CRED_IDX.ID$MASK to ""
equate W$CRED_IDX.ID$LABEL to "User Name"
