** INFORMATION ****************************************************************
*    Insert Name : I_RATECSV.H - BP
*           Type : INSERT
*       Filename : n/a
*         Prefix : n/a
** AUDIT **********************************************************************
*   Info Created : 20190527 at 16.42.49 in DEV by MANUALLY
*                : MANUALLY CREATED
*******************************************************************************
equate RATE.TYPE  to 3
equate RATE.TENOR to 4
equate RATE.CCY1  to 7
equate RATE.CCY2  to 8
equate RATE.BUY   to 9
equate RATE.SELL  to 10
equate RATE.CATEGORY to 11
