SUBROUTINE U_MSG.HTTP(TEXT, WILDCARDS)
** INFORMATION ****************************************************************
*   Routine Name : U_MSG.HTTP
*           Type : SUBROUTINE
*         Params : TEXT, WILDCARDS
*            Loc : BP
** AUDIT **********************************************************************
*   Info Updated : 20210228 at 16.21.20 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************

$INCLUDE BP I_UTIL.H
$INCLUDE BP I_HTTP.H

* EXAMPLE INPUT
*  TEXT = "NO DATA ({{1}}-{{2}})"
* WILDCARDS<1> = "ITEM"
* WILDCARDS<2> = "ITEMVALUE"
*

   CALL U_MSG.CLASS(RC$LOOKUP, TEXT, WILDCARDS)

   RETURN
END
