** INFORMATION ****************************************************************
*    Insert Name : F_LOGS.H - UTIL.BP
*           Type : INSERT
*       Filename : LOGS
*         Prefix : S_L_
** AUDIT **********************************************************************
*   Info Updated : 20210220 at 13.16.39 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_L_FILE.NAME to "LOGS"
equate S_L_LOG to 1
