** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.CACHE.H - UTIL.BP
*           Type : INSERT
*       Filename : SIENA.CACHE
*         Prefix : S_CACHE_
** AUDIT **********************************************************************
*   Info Updated : 20200921 at 19.43.22 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_CACHE_FILE.NAME to "SIENA.CACHE"
equate S_CACHE_OBJECT to 1
equate S_CACHE_FIELD to 2
equate S_CACHE_VALUE to 3
