** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.TEMP.H - UTIL.BP
*           Type : INSERT
*       Filename : SIENA.TEMP
*         Prefix : S_TEMP.
** AUDIT **********************************************************************
*   Info Updated : 20210208 at 16.23.24 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_TEMP.FILE.NAME to "SIENA.TEMP"
equate S_TEMP.OUTPUT to 1
