** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.TXN.TEMPLATES.H - UTIL.BP
*           Type : INSERT
*       Filename : SIENA.TXN.TEMPLATES
*         Prefix : S_TXN_TEMPLATE_
** AUDIT **********************************************************************
*   Info Updated : 20210209 at 11.50.26 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_TXN_TEMPLATE_FILE.NAME to "SIENA.TXN.TEMPLATES"
equate S_TXN_TEMPLATE_CONTENT to 1
