** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.IN.H - UTIL.BP
*           Type : INSERT
*       Filename : SIENA.IN
*         Prefix : S_IN.
** AUDIT **********************************************************************
*   Info Updated : 20210208 at 16.23.24 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_IN.FILE.NAME to "SIENA.IN"
equate S_IN.DATA to 1
