** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.TXN.OUT.H - UTIL.BP
*           Type : INSERT
*       Filename : SIENA.TXN.OUT
*         Prefix : S_TXN_OUT_
** AUDIT **********************************************************************
*   Info Updated : 20210228 at 14.11.29 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_TXN_OUT_FILE.NAME to "SIENA.TXN.OUT"
equate S_TXN_OUT_CONTENT to 1
