** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.PROCESSED.H - UTIL.BP
*           Type : INSERT
*       Filename : SIENA.PROCESSED
*         Prefix : S_PROC_
** AUDIT **********************************************************************
*   Info Updated : 20210228 at 00.36.29 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_PROC_FILE.NAME to "SIENA.PROCESSED"
equate S_PROC_OUTPUT to 1
