** INFORMATION ****************************************************************
*    Insert Name : F_SIENA.DEST.H - UTIL.BP
*           Type : INSERT
*       Filename : SIENA.DEST
*         Prefix : S_DEST_
** AUDIT **********************************************************************
*   Info Updated : 20210131 at 21.49.59 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate S_DEST_FILE.NAME to "SIENA.DEST"
equate S_DEST_OUTPUT to 1
