** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.WCT.TOKENS.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.WCT.TOKENS
*         Prefix : W$TOKEN.
** AUDIT **********************************************************************
*   Info Updated : 20210220 at 13.16.40 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate W$TOKEN.FILE.NAME to "UTIL.WCT.TOKENS"
equate W$TOKEN.APP.TOKEN to 1
equate W$TOKEN.CREATE.DATE to 2
equate W$TOKEN.CREATE.TIME to 3
equate W$TOKEN.UNIQUE.ID to 4
equate W$TOKEN.SESSION.TOKEN to 5
