** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.CONFIG.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.CONFIG
*         Prefix : U$CONFIG.
** AUDIT **********************************************************************
*   Info Updated : 20210220 at 13.16.38 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U$CONFIG.FILE.NAME to "UTIL.CONFIG"
equate U$CONFIG.DATA to 1
