** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.SQL.CMD.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.SQL.CMD
*         Prefix : U_SQLCMD.
** AUDIT **********************************************************************
*   Info Updated : 20210131 at 21.49.59 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_SQLCMD.FILE.NAME to "UTIL.SQL.CMD"
equate U_SQLCMD.COMMAND to 1
