** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.SQL.RESPONSE.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.SQL.RESPONSE
*         Prefix : U_SQLREP_
** AUDIT **********************************************************************
*   Info Updated : 20210217 at 17.40.22 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_SQLREP_FILE.NAME to "UTIL.SQL.RESPONSE"
equate U_SQLREP_OUTPUT to 1
