** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.LOG.EVENT.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.LOG.EVENT
*         Prefix : U_LOG_
** AUDIT **********************************************************************
*   Info Updated : 20210220 at 13.16.36 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_LOG_FILE.NAME to "UTIL.LOG.EVENT"
equate U_LOG_EVENT to 1
equate U_LOG_DATE to 2
equate U_LOG_TIME to 3
equate U_LOG_USER to 4
equate U_LOG_MSG to 5
equate U_LOG_ID to 6
equate U_LOG_CMD to 7
equate U_LOG_URI to 8
equate U_LOG_RETCD to 9
equate U_LOG_SUBR to 10
equate U_LOG_TTY to 11
equate U_LOG_USERNO to 12
equate U_LOG_PATH to 13
equate U_LOG_WHO to 14
equate U_LOG_SENTENCE to 15
equate U_LOG_HOST to 16
equate U_LOG_IP to 17
equate U_LOG_PLATFORM to 18
equate U_LOG_START to 19
equate U_LOG_STOP to 20
equate U_LOG_ELAPSED to 21
equate U_LOG_PROCESS to 22
equate U_LOG_FILE to 23
equate U_LOG_THREAD to 24
equate U_LOG_SESSIONTOKEN to 25
equate U_LOG_SESSIONUSER to 26
