** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.CSV.IN.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.CSV.IN
*         Prefix : U_CSVIN_
** AUDIT **********************************************************************
*   Info Updated : 20210131 at 21.50.00 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_CSVIN_FILE.NAME to "UTIL.CSV.IN"
equate U_CSVIN_DATA to 1
