** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.CSV.TRANSLATE.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.CSV.TRANSLATE
*         Prefix : U_CSVTX_
** AUDIT **********************************************************************
*   Info Updated : 20200921 at 19.43.22 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_CSVTX_FILE.NAME to "UTIL.CSV.TRANSLATE"
equate U_CSVTX_DATA to 1
