** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.REPORTS.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.REPORTS
*         Prefix : U_RPT.
** AUDIT **********************************************************************
*   Info Updated : 20210203 at 10.06.40 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_RPT.FILE.NAME to "UTIL.REPORTS"
equate U_RPT.REPORT to 1
