** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.LOG.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.LOG
*         Prefix : U_L_
** AUDIT **********************************************************************
*   Info Updated : 20210203 at 10.06.35 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_L_FILE.NAME to "UTIL.LOG"
equate U_L_EVENT to 1
