** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.TRANSLATE.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.TRANSLATE
*         Prefix : U_TRNS.
** AUDIT **********************************************************************
*   Info Updated : 20210220 at 13.16.38 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_TRNS.FILE.NAME to "UTIL.TRANSLATE"
equate U_TRNS.RVSERVER to 1
equate U_TRNS.UKTDATA to 2
equate U_TRNS.NIPART to 3
equate U_TRNS.NINAME to 4
equate U_TRNS.BARCHARTCOM to 5
equate U_TRNS.SIENA_BC to 6
