** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.SQL.SCRIPTS.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.SQL.SCRIPTS
*         Prefix : U_SQLSCR.
** AUDIT **********************************************************************
*   Info Updated : 20210208 at 16.23.22 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_SQLSCR.FILE.NAME to "UTIL.SQL.SCRIPTS"
equate U_SQLSCR.OUTPUT to 1
