** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.LOG.CMD.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.LOG.CMD
*         Prefix : U_LC_
** AUDIT **********************************************************************
*   Info Updated : 20210203 at 10.06.36 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_LC_FILE.NAME to "UTIL.LOG.CMD"
equate U_LC_CMD to 1
