** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.WORKFILE.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.WORKFILE
*         Prefix : U$WRK.
** AUDIT **********************************************************************
*   Info Updated : 20210220 at 13.16.37 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U$WRK.FILE.NAME to "UTIL.WORKFILE"
equate U$WRK.REPORT to 1
