** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.SCRIPTS.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.SCRIPTS
*         Prefix : U_SCRIPTS.
** AUDIT **********************************************************************
*   Info Updated : 20210131 at 21.50.00 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate U_SCRIPTS.FILE.NAME to "UTIL.SCRIPTS"
equate U_SCRIPTS.CONTENT to 1
