** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.WCT.RECV.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.WCT.RECV
*         Prefix : W$RECV.
** AUDIT **********************************************************************
*   Info Updated : 20210217 at 17.40.25 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate W$RECV.FILE.NAME to "UTIL.WCT.RECV"
equate W$RECV.CONTENT to 1
