** INFORMATION ****************************************************************
*    Insert Name : F_UTIL.WCT.TEMPLATES.H - UTIL.BP
*           Type : INSERT
*       Filename : UTIL.WCT.TEMPLATES
*         Prefix : W$TEMPLATE.
** AUDIT **********************************************************************
*   Info Updated : 20210208 at 16.23.25 in DEV by root
*                : on mercury.local (Mac)
*******************************************************************************
equate W$TEMPLATE.FILE.NAME to "UTIL.WCT.TEMPLATES"
equate W$TEMPLATE.CONTENT to 1
