* Log Info Template - First Version
equate U_LOG_EVENT    to 1
equate U_LOG_DATE     to 2
equate U_LOG_TIME     to 3
equate U_LOG_USER     to 4
equate U_LOG_MSG      to 5
equate U_LOG_ID       to 6
equate U_LOG_CMD      to 7
equate U_LOG_URI      to 8
equate U_LOG_RETCD    to 9
equate U_LOG_SUBR     to 10
equate U_LOG_TTY      to 11
equate U_LOG_USERNO   to 12
equate U_LOG_PATH     to 13
equate U_LOG_WHO      to 14
equate U_LOG_SENTANCE to 15
