* UTIL.BP UTIL.H
equate U_SEP to "~"
equate U_TRUNC to "-"
equate U_PROP_SEP to "="
equate U_PREF to "M "
equate U_BOLD_ON to -58
equate U_BOLD_OFF to -59
equate U_BLINK_ON to -5
equate U_BLINK_OFF to -6
equate U_REVERSE_ON to -13
equate U_REVERSE_OFF to -14
equate U_UNDERLINE_ON to -15
equate U_UNDERLINE_OFF to -16
equate U_CLEAR_SCREEN to -1
equate U_CLEAR_LINE   to -4
equate U_SET_FG_COLOUR to -37  ;* Set foreground colour
equate U_SET_BG_COLOUR to -38  ;* Set background colour
* Colours
equate U_COL_BLACK  to               0
equate U_COL_BLUE     to             1
equate U_COL_GREEN       to          2
equate U_COL_CYAN        to          3
equate U_COL_RED          to         4
equate U_COL_MAGENTA       to        5
equate U_COL_BROWN         to        6
equate U_COL_WHITE         to        7
equate U_COL_GREY           to       8
equate U_COL_BRIGHT_BLUE    to       9
equate U_COL_BRIGHT_GREEN   to      10
equate U_COL_BRIGHT_CYAN    to      11
equate U_COL_BRIGHT_RED     to      12
equate U_COL_BRIGHT_MAGENTA  to     13
equate U_COL_YELLOW          to     14
equate U_COL_BRIGHT_WHITE    to     15
* Log Info Template
equate U_LOG_EVENT    to 1
equate U_LOG_DATE     to 2
equate U_LOG_TIME     to 3
equate U_LOG_USER     to 4
equate U_LOG_MSG      to 5
equate U_LOG_ID       to 6
equate U_LOG_CMD      to 7
equate U_LOG_URI      to 8
equate U_LOG_RETCD    to 9
equate U_LOG_SUBR     to 10
equate U_LOG_TTY      to 11
equate U_LOG_USERNO   to 12
equate U_LOG_PATH     to 13
equate U_LOG_WHO      to 14
equate U_LOG_SENTANCE to 15
