SUBROUTINE U_CRT.ACTION(ACTION, TEXT)
$INCLUDE UTIL.BP UTIL.H
   IN.TEXT = TEXT
   TEXT = CONVERT(@AM, "^", TEXT)
   TEXT = CONVERT(@VM, "]", TEXT)
   CALL U_CRT("[":@(U_BOLD_ON):UPCASE(ACTION)"L#10":@(U_BOLD_OFF):"][":TEXT:"]")
   TEXT = IN.TEXT
   RETURN
END
